//
//  User.swift
//  Muse
//
//  Created by Aidan Blancas on 11/7/24.
//

import Foundation

struct User: Identifiable, Codable {
    var id: String // Unique ID generated by Firebase Authentication
    var displayName: String
    var email: String
    var profilePictureURL: String? // Optional URL for profile picture
    var bio: String? // Optional bio or description

}

